name: personal_notes_app
description: Simple offline-first personal notes app demonstrating locorda
publish_to: none
version: 0.1.0-dev

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Drift (SQLite) storage
  drift: ^2.19.0
  drift_flutter: ^0.2.0
  
  # Solid AUTH
  # TODO: Use published version when available
  solid_auth:
    git:
      url: https://github.com/kkalass/solid_auth.git
      ref: feat/migrate-to-bdaya-oidc-security-fix
      
  # Solid CRDT Sync packages
  locorda:
    path: ../
  locorda_annotations:
    path: ../../locorda_annotations
  locorda_core:
    path: ../../locorda_core
  locorda_solid_auth:
    path: ../../locorda_solid_auth
  locorda_solid:
    path: ../../locorda_solid
  locorda_solid_ui:
    path: ../../locorda_solid_ui
  locorda_drift:
    path: ../../locorda_drift
    
  # RDF mapping
  rdf_core: ^0.9.23
  rdf_mapper: ^0.10.4
  rdf_vocabularies_schema: ^0.4.5
  rdf_vocabularies_core: ^0.4.5
  rdf_mapper_annotations: ^0.10.4
  
  # UI
  flutter_chips_input: ^2.0.0

  # Reactive streams
  rxdart: ^0.28.0

  # Logging
  logging: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.0
  drift_dev: ^2.19.0
  rdf_mapper_generator: ^0.10.9

flutter:
  uses-material-design: true

  