name: locorda_core
description: Locorda Core - Platform-agnostic CRDT synchronization engine
version: 0.9.15-dev
homepage: https://locorda.dev/
repository: https://github.com/locorda/locorda
issue_tracker: https://github.com/locorda/locorda/issues
documentation: https://locorda.dev/
publish_to: none
publisher: locorda.dev

topics:
  - rdf
  - linked-data
  - semantic-web
  - crdt
  - solid

environment:
  sdk: ^3.6.0

dependencies:
  logging: ^1.3.0
  crypto: ^3.0.3

  # RDF 
  rdf_core: ^0.9.15
  

dev_dependencies:
  test: ^1.24.0
  lints: ">=5.1.1 <7.0.0"
  build_runner: ^2.4.15
  rdf_vocabulary_to_dart: ^0.9.2
  