name: locorda

repository: https://github.com/kkalass/locorda

packages:
  - packages/**

# Global dependency overrides that will be applied to all packages
dependency_overrides:
  oidc_core:
    git:
      url: https://github.com/kkalass/oidc.git
      ref: fix/oidc-hook-execute-stack-overflow
      path: packages/oidc_core

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:
  analyze:
    run: dart analyze .
    description: Run analysis for all packages.

  test:
    run: dart test
    description: Run tests for all packages.

  format:
    run: dart format .
    description: Run formatting for all packages.

  lint:
    run: dart analyze && dart format --set-exit-if-changed .
    description: Run linting (analyze + format check) for all packages.

  clean:
    run: dart pub get
    description: Clean and get dependencies for all packages.

  version:
    run: melos version
    description: Update package versions with conventional commits and changelog generation.

  publish:
    run: melos publish
    description: Publish all packages to pub.dev (with confirmations).

  release:
    run: melos version --no-git-tag-version && melos publish --dry-run
    description: Preview a full release (version + publish preview).