name: locorda_workspace
description: Workspace for the locorda monorepo
version: 0.9.15-dev
homepage: https://kkalass.github.io/locorda/
repository: https://github.com/kkalass/locorda
issue_tracker: https://github.com/kkalass/locorda/issues
documentation: https://kkalass.github.io/locorda/
publish_to: none

environment:
  sdk: ^3.6.0

dev_dependencies:
  melos: ^6.1.0
