name: locorda_workspace
description: Workspace for the locorda monorepo
version: 0.9.15-dev
homepage: https://locorda.dev/
repository: https://github.com/locorda/locorda
issue_tracker: https://github.com/locorda/locorda/issues
documentation: https://locorda.dev/
publish_to: none

environment:
  sdk: ^3.6.0

dev_dependencies:
  melos: ^6.1.0
  test: ^1.26.3
