name: locorda_solid
description: Locorda Solid - Solid Pod backend implementation for locorda CRDT synchronization
version: 0.9.15-dev
homepage: https://locorda.dev/
repository: https://github.com/locorda/locorda
issue_tracker: https://github.com/locorda/locorda/issues
documentation: https://locorda.dev/
publish_to: none

topics:
  - rdf
  - linked-data
  - semantic-web
  - crdt
  - solid

environment:
  sdk: ^3.6.0

dependencies:
  logging: ^1.2.0

  # Core locorda dependencies
  locorda_core:
    path: ../locorda_core

  # HTTP client for Solid Pod communication
  http: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ">=5.1.1 <7.0.0"