name: locorda_solid_auth
description: Locorda Solid Auth - Solid authentication implementation for locorda using solid-auth
version: 0.1.0-dev
homepage: https://locorda.dev/
repository: https://github.com/locorda/locorda
issue_tracker: https://github.com/locorda/locorda/issues
publish_to: none
publisher: locorda.dev

topics:
  - solid
  - authentication
  - oidc

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  logging: ^1.3.0
  locorda_core:
    path: ../locorda_core
  locorda_solid:
    path: ../locorda_solid
  # Solid authentication
  # TODO: Use published version when available
  solid_auth:
    git:
      url: https://github.com/kkalass/solid_auth.git
      ref: feat/dpop-worker-thread-support
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ">=5.1.1 <7.0.0"

flutter:
  generate: true

# TODO: Remove when solid_auth and a fixed oidc_core are published
dependency_overrides:
  oidc_core:
    git:
      url: https://github.com/kkalass/oidc.git
      ref: fix/oidc-hook-execute-stack-overflow
      path: packages/oidc_core
