name: locorda_worker
description: Worker infrastructure for Locorda - Platform-agnostic isolate/worker architecture for offloading heavy operations (CRDT, DB, HTTP) to separate thread.
version: 0.1.0-dev
publish_to: none
publisher: locorda.dev
homepage: https://github.com/locorda/locorda

environment:
  sdk: '>=3.5.0 <4.0.0'
  

dependencies:
  locorda_core:
    path: ../locorda_core
  
  # RDF mapping
  rdf_core: ^0.9.24

  # Web Worker support (modern API)
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.13
  test: ^1.24.0

topics:
  - rdf
  - crdt
  - solid
  - offline-first
  - sync