name: locorda_annotations
description: Locorda Annotations - CRDT merge strategy annotations for code generation
version: 0.1.0-dev
publisher: locorda.dev
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  rdf_mapper_annotations: ^0.10.4
  locorda_core: 
    path: ../locorda_core

dev_dependencies:
  test: ^1.21.0

topics:
  - rdf
  - crdt
  - solid
  - annotations
  - codegen