// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
//
// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field

import 'package:locorda_rdf_mapper/mapper.dart';

import 'package:rdf_mapper_examples/advanced.dart' as advanced;
import 'package:rdf_mapper_examples/advanced.rdf_mapper.g.dart' as armg;
import 'package:rdf_mapper_examples/collections.dart' as collections;
import 'package:rdf_mapper_examples/collections.rdf_mapper.g.dart' as crmg;
import 'package:rdf_mapper_examples/lossless.dart' as lossless;
import 'package:rdf_mapper_examples/lossless.rdf_mapper.g.dart' as lrmg;
import 'package:rdf_mapper_examples/quick_start.dart' as quick_start;
import 'package:rdf_mapper_examples/quick_start.rdf_mapper.g.dart' as qsrmg;

/// Initializes and returns an RdfMapper with mappers registered.
///
/// [rdfMapper] An optional RdfMapper instance to use. If not provided, a new one will be created.
/// * [baseUriProvider]
RdfMapper initRdfMapper({
  RdfMapper? rdfMapper,
  required String Function() baseUriProvider,
}) {
  if (rdfMapper == null) {
    rdfMapper = RdfMapper.withDefaultRegistry();
  }
  var registry = rdfMapper.registry;

  registry.registerMapper<advanced.Book>(
    armg.BookMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<advanced.ISBN>(armg.ISBNMapper());
  registry.registerMapper<advanced.BookFormat>(armg.BookFormatMapper());
  registry.registerMapper<collections.Book>(
    crmg.BookMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<collections.Chapter>(crmg.ChapterMapper());
  registry.registerMapper<collections.ReviewEntry>(crmg.ReviewEntryMapper());
  registry.registerMapper<collections.Review>(crmg.ReviewMapper());
  registry.registerMapper<lossless.BookLossless>(
    lrmg.BookLosslessMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<quick_start.Book>(
    qsrmg.BookMapper(baseUriProvider: baseUriProvider),
  );

  return rdfMapper;
}
