// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: lib/lossless.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'package:rdf_mapper_examples/lossless.dart' as lossless;
import 'package:locorda_rdf_terms_schema/schema.dart';

/// Generated mapper for [lossless.BookLossless] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `lossless.BookLossless`.
class BookLosslessMapper
    implements GlobalResourceMapper<lossless.BookLossless> {
  static final RegExp _regex = RegExp(
    r'^(?<baseUri>.*)/lossless-books/(?<isbn>[^/]*)$',
  );

  final String Function() _baseUriProvider;

  /// Constructor
  const BookLosslessMapper({required String Function() baseUriProvider})
    : _baseUriProvider = baseUriProvider;

  @override
  IriTerm? get typeIri =>
      const IriTerm('https://example.org/vocab/LosslessBook');

  @override
  lossless.BookLossless fromRdfResource(
    IriTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final RegExpMatch? match = _regex.firstMatch(subject.value);

    final iriParts = {
      for (var name in (match?.groupNames ?? const <String>[]))
        name: match?.namedGroup(name) ?? '',
    };

    final isbn = iriParts['isbn'];
    if (isbn == null) {
      throw DeserializationException(
        'Missing required IRI part: isbn in IRI ${subject.value}',
      );
    }
    final String title = reader.require(SchemaBook.name);
    final String author = reader.require(SchemaBook.author);

    return lossless.BookLossless(isbn: isbn, title: title, author: author);
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    lossless.BookLossless resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = context.createIriTerm(_buildIri(resource));

    return context
        .resourceBuilder(subject)
        .addValue(SchemaBook.name, resource.title)
        .addValue(SchemaBook.author, resource.author)
        .build();
  }

  /// Builds the IRI for a resource instance using the IRI template.
  String _buildIri(lossless.BookLossless resource) {
    final isbn = resource.isbn;
    final baseUri = _baseUriProvider();
    return '${baseUri}/lossless-books/${isbn}';
  }
}
