// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: lib/quick_start.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'package:rdf_mapper_examples/quick_start.dart' as quick_start;
import 'package:locorda_rdf_terms_schema/schema.dart';

/// Generated mapper for [quick_start.Book] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `quick_start.Book`.
class BookMapper implements GlobalResourceMapper<quick_start.Book> {
  static final RegExp _regex = RegExp(r'^(?<baseUri>.*)/books/(?<isbn>[^/]*)$');

  final String Function() _baseUriProvider;

  /// Constructor
  const BookMapper({required String Function() baseUriProvider})
    : _baseUriProvider = baseUriProvider;

  @override
  IriTerm? get typeIri => SchemaBook.classIri;

  @override
  quick_start.Book fromRdfResource(
    IriTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final RegExpMatch? match = _regex.firstMatch(subject.value);

    final iriParts = {
      for (var name in (match?.groupNames ?? const <String>[]))
        name: match?.namedGroup(name) ?? '',
    };

    final isbn = iriParts['isbn'];
    if (isbn == null) {
      throw DeserializationException(
        'Missing required IRI part: isbn in IRI ${subject.value}',
      );
    }
    final String title = reader.require(SchemaBook.name);
    final String author = reader.require(SchemaBook.author);
    final DateTime published = reader.require(SchemaBook.datePublished);

    return quick_start.Book(
      isbn: isbn,
      title: title,
      author: author,
      published: published,
    );
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    quick_start.Book resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = context.createIriTerm(_buildIri(resource));

    return context
        .resourceBuilder(subject)
        .addValue(SchemaBook.name, resource.title)
        .addValue(SchemaBook.author, resource.author)
        .addValue(SchemaBook.datePublished, resource.published)
        .build();
  }

  /// Builds the IRI for a resource instance using the IRI template.
  String _buildIri(quick_start.Book resource) {
    final isbn = resource.isbn;
    final baseUri = _baseUriProvider();
    return '${baseUri}/books/${isbn}';
  }
}
