name: locorda_solid_ui
description: Locorda UI - Flutter UI components for locorda including login forms and sync widgets
version: 0.9.15-dev
homepage: https://locorda.dev/
repository: https://github.com/locorda/locorda
issue_tracker: https://github.com/locorda/locorda/issues
publish_to: none
publisher: locorda.dev

topics:
  - solid
  - flutter
  - crdt

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  locorda_core:
    path: ../locorda_core
  locorda_solid_auth:
    path: ../locorda_solid_auth

  # Logging
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ">=5.1.1 <7.0.0"