name: locorda_solid_auth_worker
description: Solid authentication bridge for Locorda worker architecture. Synchronizes auth state from main thread to worker isolate.
version: 0.1.0-dev
publish_to: none
publisher: locorda.dev
homepage: https://github.com/locorda/locorda

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  locorda_core:
    path: ../locorda_core
  locorda_worker:
    path: ../locorda_worker
  locorda_solid:
    path: ../locorda_solid
# Solid AUTH
  # TODO: Use published version when available
  solid_auth:
    git:
      url: https://github.com/kkalass/solid_auth.git
      ref: feat/dpop-worker-thread-support
  
  
  # RDF mapping
  rdf_core: ^0.9.24


dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.24.0

topics:
  - rdf
  - crdt
  - solid
  - offline-first
  - sync