name: locorda_drift
description: Locorda Drift - SQLite storage implementation for locorda_core
version: 0.1.0-dev
homepage: https://locorda.dev/
repository: https://github.com/locorda/locorda
issue_tracker: https://github.com/locorda/locorda/issues
publish_to: none
publisher: locorda.dev

topics:
  - solid
  - crdt
  - storage
  - drift
  - sqlite

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  locorda_core:
    path: ../locorda_core
  drift: ^2.28.1
  drift_flutter: ^0.2.6
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.0
  path: ^1.9.0
  sqlite3: ^2.4.0
  rdf_core: ^0.9.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.20.0
  build_runner: ^2.4.0
  lints: ">=5.1.1 <7.0.0"
  test: ^1.25.0
  