name: locorda
description: Bring your own persistence layer and make it syncable to a Solid Pod - Local-first CRDT synchronization
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  locorda_core:
    path: ../locorda_core
  locorda_annotations:
    path: ../locorda_annotations
  locorda_drift:
    path: ../locorda_drift
  locorda_solid_auth:
    path: ../locorda_solid_auth
  locorda_ui:
    path: ../locorda_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

topics:
  - rdf
  - crdt
  - solid
  - local-first
  - sync