name: locorda
description: Locorda - Sync offline-first apps using your user's remote storage
version: 0.1.0+1
publish_to: none
publisher: locorda.dev

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  locorda_core:
    path: ../locorda_core
  locorda_annotations:
    path: ../locorda_annotations
  locorda_drift:
    path: ../locorda_drift
  locorda_solid_auth:
    path: ../locorda_solid_auth
  locorda_solid_ui:
    path: ../locorda_solid_ui

  # RDF mapping
  rdf_core: ^0.9.15
  rdf_mapper: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true

topics:
  - rdf
  - crdt
  - solid
  - offline-first
  - sync