name: Publish to pub.dev

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          
      # Install workspace dependencies
      - name: Install workspace dependencies
        run: dart pub get
        
      # Bootstrap melos workspace  
      - name: Bootstrap melos workspace
        run: dart pub run melos bootstrap
        
      # Publish dry run for all packages
      - name: Publish dry run (all packages)
        run: dart pub run melos publish --dry-run
        
      - name: Publish (manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "To publish packages, run 'dart pub run melos publish' manually with credentials."
          echo "Note: Only locorda_core is currently publishable."
          echo "UI and auth packages are marked with 'publish_to: none'."
          
      # Note: Auto-publishing with melos requires more complex setup
      # Recommend manual publishing for multipackage repos
