// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: lib/collections.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'package:mapper_annotations_examples/collections.dart' as collections;
import 'package:locorda_rdf_terms_schema/schema.dart';

/// Generated mapper for [collections.Book] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `collections.Book`.
class BookMapper implements GlobalResourceMapper<collections.Book> {
  static final RegExp _regex = RegExp(
    r'^https://example\.org/books/(?<isbn>[^/]*)$',
  );

  /// Constructor
  const BookMapper();

  @override
  IriTerm? get typeIri => SchemaBook.classIri;

  @override
  collections.Book fromRdfResource(
    IriTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final RegExpMatch? match = _regex.firstMatch(subject.value);

    final iriParts = {
      for (var name in (match?.groupNames ?? const <String>[]))
        name: match?.namedGroup(name) ?? '',
    };

    final isbn = iriParts['isbn'];
    if (isbn == null) {
      throw DeserializationException(
        'Missing required IRI part: isbn in IRI ${subject.value}',
      );
    }
    final String title = reader.require(SchemaBook.name);
    final List<String> tags = reader.requireCollection<List<String>, String>(
      SchemaBook.keywords,
      UnorderedItemsListMapper.new,
    );
    final Set<String> authors = reader.requireCollection<Set<String>, String>(
      SchemaBook.author,
      UnorderedItemsSetMapper.new,
    );
    final List<collections.Chapter> chapters = reader
        .requireCollection<List<collections.Chapter>, collections.Chapter>(
          SchemaBook.hasPart,
          RdfListMapper.new,
        );

    return collections.Book(
      isbn: isbn,
      title: title,
      tags: tags,
      authors: authors,
      chapters: chapters,
    );
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    collections.Book resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = context.createIriTerm(_buildIri(resource));

    return context
        .resourceBuilder(subject)
        .addValue(SchemaBook.name, resource.title)
        .addCollection<List<String>, String>(
          SchemaBook.keywords,
          resource.tags,
          UnorderedItemsListMapper.new,
        )
        .addCollection<Set<String>, String>(
          SchemaBook.author,
          resource.authors,
          UnorderedItemsSetMapper.new,
        )
        .addCollection<List<collections.Chapter>, collections.Chapter>(
          SchemaBook.hasPart,
          resource.chapters,
          RdfListMapper.new,
        )
        .build();
  }

  /// Builds the IRI for a resource instance using the IRI template.
  String _buildIri(collections.Book resource) {
    final isbn = resource.isbn;
    return 'https://example.org/books/${isbn}';
  }
}

/// Generated mapper for [collections.Chapter] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `collections.Chapter`.
class ChapterMapper implements LocalResourceMapper<collections.Chapter> {
  /// Constructor
  const ChapterMapper();

  @override
  IriTerm? get typeIri => SchemaChapter.classIri;

  @override
  collections.Chapter fromRdfResource(
    BlankNodeTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final String title = reader.require(SchemaChapter.name);

    return collections.Chapter(title: title);
  }

  @override
  (BlankNodeTerm, Iterable<Triple>) toRdfResource(
    collections.Chapter resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();

    return context
        .resourceBuilder(subject)
        .addValue(SchemaChapter.name, resource.title)
        .build();
  }
}
