// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: lib/custom_literal.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'package:mapper_annotations_examples/custom_literal.dart' as cl;
import 'package:locorda_rdf_terms_core/rdf.dart' as rdf;
import 'package:locorda_rdf_mapper_annotations/annotations.dart';

/// Generated mapper for [cl.ISBN] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF terms for iri terms of type cl.ISBN.
class ISBNMapper implements LiteralTermMapper<cl.ISBN> {
  final IriTerm? datatype = null;

  const ISBNMapper();

  @override
  cl.ISBN fromRdfTerm(
    LiteralTerm term,
    DeserializationContext context, {
    bool bypassDatatypeCheck = false,
  }) {
    final String value = context.fromLiteralTerm(
      term,
      bypassDatatypeCheck: bypassDatatypeCheck,
    );

    return cl.ISBN(value);
  }

  @override
  LiteralTerm toRdfTerm(
    cl.ISBN value,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    return context.toLiteralTerm(value.value);
  }
}

/// Generated mapper for [cl.Temperature] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF terms for iri terms of type cl.Temperature.
class TemperatureMapper implements LiteralTermMapper<cl.Temperature> {
  final IriTerm? datatype = const IriTerm('http://example.org/temperature');

  const TemperatureMapper();

  @override
  cl.Temperature fromRdfTerm(
    LiteralTerm term,
    DeserializationContext context, {
    bool bypassDatatypeCheck = false,
  }) {
    if (!bypassDatatypeCheck &&
        term.datatype != const IriTerm('http://example.org/temperature')) {
      throw DeserializerDatatypeMismatchException(
        'Failed to parse cl.Temperature: ${term.value}. ',
        actual: term.datatype,
        expected: const IriTerm('http://example.org/temperature'),
        targetType: cl.Temperature,
        mapperRuntimeType: this.runtimeType,
      );
    }
    return cl.Temperature.parse(LiteralContent.fromLiteralTerm(term));
  }

  @override
  LiteralTerm toRdfTerm(
    cl.Temperature value,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    return value.formatCelsius().toLiteralTerm(datatype);
  }
}
