// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: lib/enum_mapping.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'package:mapper_annotations_examples/enum_mapping.dart' as enum_mapping;
import 'package:locorda_rdf_terms_schema/schema.dart';

/// Generated mapper for [enum_mapping.Book] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `enum_mapping.Book`.
class BookMapper implements GlobalResourceMapper<enum_mapping.Book> {
  static final RegExp _regex = RegExp(
    r'^https://example\.org/books/(?<isbn>[^/]*)$',
  );

  /// Constructor
  const BookMapper();

  @override
  IriTerm? get typeIri => SchemaBook.classIri;

  @override
  enum_mapping.Book fromRdfResource(
    IriTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final RegExpMatch? match = _regex.firstMatch(subject.value);

    final iriParts = {
      for (var name in (match?.groupNames ?? const <String>[]))
        name: match?.namedGroup(name) ?? '',
    };

    final isbn = iriParts['isbn'];
    if (isbn == null) {
      throw DeserializationException(
        'Missing required IRI part: isbn in IRI ${subject.value}',
      );
    }
    final String title = reader.require(SchemaBook.name);
    final enum_mapping.BookFormat format = reader.require(
      SchemaBook.bookFormat,
    );

    return enum_mapping.Book(isbn: isbn, title: title, format: format);
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    enum_mapping.Book resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = context.createIriTerm(_buildIri(resource));

    return context
        .resourceBuilder(subject)
        .addValue(SchemaBook.name, resource.title)
        .addValue(SchemaBook.bookFormat, resource.format)
        .build();
  }

  /// Builds the IRI for a resource instance using the IRI template.
  String _buildIri(enum_mapping.Book resource) {
    final isbn = resource.isbn;
    return 'https://example.org/books/${isbn}';
  }
}

/// Generated mapper for [enum_mapping.BookFormat] enum IRIs.
///
/// This mapper handles serialization and deserialization between enum constants
/// and RDF IRI terms for enum type enum_mapping.BookFormat.
class BookFormatMapper implements IriTermMapper<enum_mapping.BookFormat> {
  static final RegExp _regex = RegExp(r'^https://schema\.org/(?<value>[^/]*)$');

  /// Constructor
  const BookFormatMapper();

  @override
  enum_mapping.BookFormat fromRdfTerm(
    IriTerm term,
    DeserializationContext context,
  ) {
    /// Parses IRI parts from a complete IRI using a template.
    final RegExpMatch? match = _regex.firstMatch(term.value);

    if (match == null) {
      throw DeserializationException(
        'Unknown enum_mapping.BookFormat IRI: ${term.value}',
      );
    }

    final iriParts = {
      for (var name in match.groupNames) name: match.namedGroup(name) ?? '',
    };
    final enumValue = iriParts['value'];
    if (enumValue == null) {
      throw DeserializationException(
        'Missing required IRI part: value in IRI ${term.value}',
      );
    }

    return switch (enumValue) {
      'Hardcover' => enum_mapping.BookFormat.hardcover,
      'Paperback' => enum_mapping.BookFormat.paperback,
      'EBook' => enum_mapping.BookFormat.ebook,
      _ => throw DeserializationException(
        'Unknown enum_mapping.BookFormat IRI: ${term.value}',
      ),
    };
  }

  @override
  IriTerm toRdfTerm(
    enum_mapping.BookFormat value,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) => switch (value) {
    enum_mapping.BookFormat.hardcover => context.createIriTerm(
      _buildIri('Hardcover'),
    ),
    enum_mapping.BookFormat.paperback => context.createIriTerm(
      _buildIri('Paperback'),
    ),
    enum_mapping.BookFormat.ebook => context.createIriTerm(_buildIri('EBook')),
  };

  /// Generates the complete IRI for a given enum value
  String _buildIri(String value) {
    return 'https://schema.org/${value}';
  }
}
