// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
//
// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field

import 'package:locorda_rdf_mapper/mapper.dart';

import 'package:mapper_annotations_examples/collections.dart' as collections;
import 'package:mapper_annotations_examples/collections.rdf_mapper.g.dart'
    as crmg;
import 'package:mapper_annotations_examples/custom_literal.dart' as cl;
import 'package:mapper_annotations_examples/custom_literal.rdf_mapper.g.dart'
    as clrmg;
import 'package:mapper_annotations_examples/enum_mapping.dart' as enum_mapping;
import 'package:mapper_annotations_examples/enum_mapping.rdf_mapper.g.dart'
    as emrmg;
import 'package:mapper_annotations_examples/global_resource.dart' as gr;
import 'package:mapper_annotations_examples/global_resource.rdf_mapper.g.dart'
    as grrmg;
import 'package:mapper_annotations_examples/iri_strategy.dart' as iri_strategy;
import 'package:mapper_annotations_examples/iri_strategy.rdf_mapper.g.dart'
    as isrmg;
import 'package:mapper_annotations_examples/local_resource.dart' as lr;
import 'package:mapper_annotations_examples/local_resource.rdf_mapper.g.dart'
    as lrrmg;
import 'package:mapper_annotations_examples/map_entries.dart' as map_entries;
import 'package:mapper_annotations_examples/map_entries.rdf_mapper.g.dart'
    as mermg;
import 'package:mapper_annotations_examples/property_annotations.dart' as pa;
import 'package:mapper_annotations_examples/property_annotations.rdf_mapper.g.dart'
    as parmg;
import 'package:mapper_annotations_examples/unmapped_triples.dart' as ut;
import 'package:mapper_annotations_examples/unmapped_triples.rdf_mapper.g.dart'
    as utrmg;

/// Initializes and returns an RdfMapper with mappers registered.
///
/// [rdfMapper] An optional RdfMapper instance to use. If not provided, a new one will be created.
/// * [baseUriProvider]
RdfMapper initRdfMapper({
  RdfMapper? rdfMapper,
  required String Function() baseUriProvider,
}) {
  if (rdfMapper == null) {
    rdfMapper = RdfMapper.withDefaultRegistry();
  }
  var registry = rdfMapper.registry;

  registry.registerMapper<collections.Book>(crmg.BookMapper());
  registry.registerMapper<collections.Chapter>(crmg.ChapterMapper());
  registry.registerMapper<cl.ISBN>(clrmg.ISBNMapper());
  registry.registerMapper<cl.Temperature>(clrmg.TemperatureMapper());
  registry.registerMapper<enum_mapping.Book>(emrmg.BookMapper());
  registry.registerMapper<enum_mapping.BookFormat>(emrmg.BookFormatMapper());
  registry.registerMapper<gr.Book>(grrmg.BookMapper());
  registry.registerMapper<iri_strategy.User>(isrmg.UserMapper());
  registry.registerMapper<iri_strategy.Product>(
    isrmg.ProductMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<lr.Chapter>(lrrmg.ChapterMapper());
  registry.registerMapper<map_entries.Book>(mermg.BookMapper());
  registry.registerMapper<map_entries.TranslationEntry>(
    mermg.TranslationEntryMapper(),
  );
  registry.registerMapper<pa.Book>(parmg.BookMapper());
  registry.registerMapper<ut.Book>(utrmg.BookMapper());

  return rdfMapper;
}
