// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: lib/iri_strategy.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'package:mapper_annotations_examples/iri_strategy.dart' as iri_strategy;
import 'package:locorda_rdf_terms_schema/schema.dart';

/// Generated mapper for [iri_strategy.User] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `iri_strategy.User`.
class UserMapper implements GlobalResourceMapper<iri_strategy.User> {
  static final RegExp _regex = RegExp(
    r'^https://example\.org/users/(?<username>[^/]*)$',
  );

  /// Constructor
  const UserMapper();

  @override
  IriTerm? get typeIri => SchemaPerson.classIri;

  @override
  iri_strategy.User fromRdfResource(
    IriTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final RegExpMatch? match = _regex.firstMatch(subject.value);

    final iriParts = {
      for (var name in (match?.groupNames ?? const <String>[]))
        name: match?.namedGroup(name) ?? '',
    };

    final username = iriParts['username'];
    if (username == null) {
      throw DeserializationException(
        'Missing required IRI part: username in IRI ${subject.value}',
      );
    }
    final String fullName = reader.require(SchemaPerson.name);

    return iri_strategy.User(username: username, fullName: fullName);
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    iri_strategy.User resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = context.createIriTerm(_buildIri(resource));

    return context
        .resourceBuilder(subject)
        .addValue(SchemaPerson.name, resource.fullName)
        .build();
  }

  /// Builds the IRI for a resource instance using the IRI template.
  String _buildIri(iri_strategy.User resource) {
    final username = resource.username;
    return 'https://example.org/users/${username}';
  }
}

/// Generated mapper for [iri_strategy.Product] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `iri_strategy.Product`.
class ProductMapper implements GlobalResourceMapper<iri_strategy.Product> {
  static final RegExp _regex = RegExp(
    r'^(?<baseUri>.*)/products/(?<id>[^/]*)$',
  );

  final String Function() _baseUriProvider;

  /// Constructor
  const ProductMapper({required String Function() baseUriProvider})
    : _baseUriProvider = baseUriProvider;

  @override
  IriTerm? get typeIri => SchemaProduct.classIri;

  @override
  iri_strategy.Product fromRdfResource(
    IriTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final RegExpMatch? match = _regex.firstMatch(subject.value);

    final iriParts = {
      for (var name in (match?.groupNames ?? const <String>[]))
        name: match?.namedGroup(name) ?? '',
    };

    final id = iriParts['id'];
    if (id == null) {
      throw DeserializationException(
        'Missing required IRI part: id in IRI ${subject.value}',
      );
    }
    final String name = reader.require(SchemaProduct.name);

    return iri_strategy.Product(id: id, name: name);
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    iri_strategy.Product resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = context.createIriTerm(_buildIri(resource));

    return context
        .resourceBuilder(subject)
        .addValue(SchemaProduct.name, resource.name)
        .build();
  }

  /// Builds the IRI for a resource instance using the IRI template.
  String _buildIri(iri_strategy.Product resource) {
    final id = resource.id;
    final baseUri = _baseUriProvider();
    return '${baseUri}/products/${id}';
  }
}
