// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: lib/map_entries.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'package:mapper_annotations_examples/map_entries.dart' as map_entries;
import 'package:locorda_rdf_terms_schema/schema.dart';

/// Generated mapper for [map_entries.Book] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `map_entries.Book`.
class BookMapper implements GlobalResourceMapper<map_entries.Book> {
  static final RegExp _regex = RegExp(
    r'^https://example\.org/books/(?<isbn>[^/]*)$',
  );

  /// Constructor
  const BookMapper();

  @override
  IriTerm? get typeIri => SchemaBook.classIri;

  @override
  map_entries.Book fromRdfResource(
    IriTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final RegExpMatch? match = _regex.firstMatch(subject.value);

    final iriParts = {
      for (var name in (match?.groupNames ?? const <String>[]))
        name: match?.namedGroup(name) ?? '',
    };

    final isbn = iriParts['isbn'];
    if (isbn == null) {
      throw DeserializationException(
        'Missing required IRI part: isbn in IRI ${subject.value}',
      );
    }
    final String title = reader.require(SchemaBook.name);
    final Map<String, String> translations = reader
        .collect<map_entries.TranslationEntry, Map<String, String>>(
          SchemaBook.review,
          (it) => {for (var vc in it) vc.language: vc.text},
        );

    return map_entries.Book(
      isbn: isbn,
      title: title,
      translations: translations,
    );
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    map_entries.Book resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = context.createIriTerm(_buildIri(resource));

    return context
        .resourceBuilder(subject)
        .addValue(SchemaBook.name, resource.title)
        .addValues<map_entries.TranslationEntry>(
          SchemaBook.review,
          resource.translations.entries.map(
            (e) => map_entries.TranslationEntry(language: e.key, text: e.value),
          ),
        )
        .build();
  }

  /// Builds the IRI for a resource instance using the IRI template.
  String _buildIri(map_entries.Book resource) {
    final isbn = resource.isbn;
    return 'https://example.org/books/${isbn}';
  }
}

/// Generated mapper for [map_entries.TranslationEntry] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `map_entries.TranslationEntry`.
class TranslationEntryMapper
    implements LocalResourceMapper<map_entries.TranslationEntry> {
  /// Constructor
  const TranslationEntryMapper();

  @override
  IriTerm? get typeIri => SchemaReview.classIri;

  @override
  map_entries.TranslationEntry fromRdfResource(
    BlankNodeTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final String language = reader.require(SchemaReview.inLanguage);
    final String text = reader.require(SchemaReview.reviewBody);

    return map_entries.TranslationEntry(language: language, text: text);
  }

  @override
  (BlankNodeTerm, Iterable<Triple>) toRdfResource(
    map_entries.TranslationEntry resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();

    return context
        .resourceBuilder(subject)
        .addValue(SchemaReview.inLanguage, resource.language)
        .addValue(SchemaReview.reviewBody, resource.text)
        .build();
  }
}
