// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: lib/property_annotations.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'package:mapper_annotations_examples/property_annotations.dart' as pa;
import 'package:locorda_rdf_terms_schema/schema.dart';

/// Generated mapper for [pa.Book] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `pa.Book`.
class BookMapper implements GlobalResourceMapper<pa.Book> {
  static final RegExp _regex = RegExp(
    r'^https://example\.org/books/(?<isbn>[^/]*)$',
  );

  /// Constructor
  const BookMapper();

  @override
  IriTerm? get typeIri => SchemaBook.classIri;

  @override
  pa.Book fromRdfResource(IriTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);

    final RegExpMatch? match = _regex.firstMatch(subject.value);

    final iriParts = {
      for (var name in (match?.groupNames ?? const <String>[]))
        name: match?.namedGroup(name) ?? '',
    };

    final isbn = iriParts['isbn'];
    if (isbn == null) {
      throw DeserializationException(
        'Missing required IRI part: isbn in IRI ${subject.value}',
      );
    }
    final String title = reader.require(SchemaBook.name);
    final String? author = reader.optional(SchemaBook.author);
    final List<String> tags = reader.requireCollection<List<String>, String>(
      SchemaBook.keywords,
      UnorderedItemsListMapper.new,
    );

    return pa.Book(isbn: isbn, title: title, author: author, tags: tags);
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    pa.Book resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = context.createIriTerm(_buildIri(resource));

    return context
        .resourceBuilder(subject)
        .addValue(SchemaBook.name, resource.title)
        .when(
          resource.author != null,
          (b) => b.addValue(SchemaBook.author, resource.author),
        )
        .addCollection<List<String>, String>(
          SchemaBook.keywords,
          resource.tags,
          UnorderedItemsListMapper.new,
        )
        .build();
  }

  /// Builds the IRI for a resource instance using the IRI template.
  String _buildIri(pa.Book resource) {
    final isbn = resource.isbn;
    return 'https://example.org/books/${isbn}';
  }
}
